### ISSUE TITLE
Split "Third-Party Integration Plugins" into two categories

### ISSUE THREAD

**Issue by argenos** [obsidian-community/obsidian-hub#61]
From #60:
> I think this category should differentiate between plugins that add one specific service to Obsidian (e.g. Readwise) and plugins that enable you do generally integrate third party services to Obsidian (e.g. URI Commands), since they are similar, but distinct use cases.

## Tasks

- [ ] Create a new category file in `02.01` with the title `Plugins with Obsidian URI`
- [ ] Apply the `T - Plugin Category` template
- [ ] Move plugins that do not integrate with external services into it

**Comment by argenos** [comment]
Thanks! I've assigned the issue to you in the meantime

**Comment by Vikas3100** [comment]
Hi Argentina, 
I want to contribute in this project and want to fix this issue.
