### ISSUE TITLE
Split "Plugins to export and import markdown files" category

### ISSUE THREAD

**Issue by argenos** [obsidian-community/obsidian-hub#62]
From #60: 
> Plugins that convert content into markdown content (e.g. Tweets to Markdown)
> Plugins that convert a file into .md (e.g. a PDF into Markdown)

## Tasks

- [ ] Create one note: `Plugins to convert content into markdown`  in `02.01`
- [ ] Apply the `T - Plugin Category` template
- [ ] Rename `Plugins to export and import markdown files` to `Plugins to export markdown content`
- [ ] Move or copy exporter plugins into the new category

**Comment by twwilliams** [comment]
I'll do this if no one is already working on it.

**Comment by argenos** [comment]
Solved by #75! Thanks @twwilliams!
